### ISSUE TITLE
Derelict loader needs libName for Linux

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [ColonelThirtyTwo/dvulkan#2]
I don't have a Vulkan installation on Linux at the moment, so I don't know the Vulkan library name on Linux (or Mac, if Vulkan even exists there).

If someone knows, please leave a comment.

**Comment by Ka-lua** [comment]
I'm successfully loading vulkan on arch linux with

``` D
import std.string : fromStringz;
void* vulkanLibrary = dlopen( "libvulkan.so", RTLD_NOW);
if (!vulkanLibrary)
{
    stderr.writefln("Error loading Vulkan: %s", fromStringz(dlerror()));
    return 1;
}
scope(exit) dlclose(vulkanLibrary);

vkGetInstanceProcAddr = cast(typeof(vkGetInstanceProcAddr)) dlsym(vulkanLibrary, "vkGetInstanceProcAddr\0".ptr);
if (vkGetInstanceProcAddr is null)
{
    stderr.writefln("Error loading vkGetInstanceProcAddr: %s", fromStringz(dlerror()));
    return 1;
}
```

Does that help?

**Comment by ColonelThirtyTwo** [comment]
@Kallua Can you do `ldconfig -p | grep -Fi vulkan` and post the results? I'm a bit hesitant to load `libvulkan.so` directly since they may refer to a future major version of Vulkan which may be incompatible; it'd be better to link to, say, `libvulkan.so.1` if it exists.

**Comment by Ka-lua** [comment]
Here you go:

```
 $ ldconfig -p | grep -Fi vulkan
    libvulkan.so.1 (libc6,x86-64) => /usr/lib/libvulkan.so.1
    libvulkan.so (libc6,x86-64) => /usr/lib/libvulkan.so
```
