### ISSUE TITLE
Make DVulkanLoader.loadAllFunctions(VkDevice device) static

### ISSUE THREAD

**Issue by Ka-lua** [ColonelThirtyTwo/dvulkan#7]
Otherwise DVulkanLoader.loadAllFunctions(device) does not work because of missing this pointer.

**Comment by ParticlePeter** [comment]
I really don't understand what you have done there, but I strongly recommend you to read [API without secrets](https://software.intel.com/en-us/articles/api-without-secrets-introduction-to-vulkan-part-1).

Just think about it. When you call `DVulkanLoader.loadAllFunctions(device)` you also load the function `vkDestroyInstance`. Now the normal shutting down procedure would be `vkDestroyDevice(device)` and gone is your `vkDestroyInstance` function. So what now?
