### ISSUE TITLE
Loading vkDestroyInstance with vkGetDeviceProcAddr wrong?

### ISSUE THREAD

**Issue by Ka-lua** [ColonelThirtyTwo/dvulkan#8]
After creating an instance and calling `DVulkanLoader.loadAllFunctions(instance)` initializes `vkDestroyInstance` just fine, using `vkGetInstanceProcAddr(instance, "vkDestroyInstance")` internally.

But when creating a device and calling `DVulkanLoader.loadAllFunctions(device)`, the function internally calls `vkGetDeviceProcAddr(device, "vkDestroyInstance")` which returns null and thus resets `vkDestroyInstance` to null.

Is that a vulkan implementation error, or should we just not use `vkGetDeviceProcAddr` to retrieve `vkDestroyInstance`? I couldn't find any list which functions should be loaded with any of the two loader functions.

**Comment by ParticlePeter** [comment]
Its not a vulkan implementation error, the dvulkan function loading process is partially wrong. Additionally to vkDestroyInstance there are some more functions which should not be loaded per device, e.g. vkGetPhysicalDevice... functions.
For now your best bet is to use loadAllFunctions(VkInstance).

Edit:
I've created a pull request to fix this, until (if at all) it will be accepted you can try my fork, specifically branch vulkan-docs-v1.0.3. Follow the readme and check out devices example. If you try to create your own bindings make sure that you use vulkan-docs-v1.0.6 as the highest version, something was changed on the khronos vulkan generator afterwords. Working on that

**Comment by ParticlePeter** [comment]
I've created a pull request to fix this, until (if at all) it will be accepted you can try my fork, specifically branch vulkan-docs-v1.0.3. Follow the readme and check out devices example. If you try to create your own bindings make sure that you use vulkan-docs-v1.0.6 as the highest version, something was changed on the khronos vulkan generator afterwords. Working on that.

**Comment by Ka-lua** [comment]
Thanks, I already have made some changes locally so that the generated vulcan bindings are usable, but I haven't fixed the loadAllFunctions errors yet. But I'll try your fork next, cause public bindings are preferable to everyone writing their own.

**Comment by ParticlePeter** [comment]
Could you elaborate how your solution is supposed to help when? Please read also my first reply to Kallua in this issue, there are functions which are not supposed to be loaded through the device.
In closed issue #7 I've posted a valid example which would still break your setup.

**Comment by ColonelThirtyTwo** [comment]
The documentation for `vkGetDeviceProcAddr` (which I missed the first time around) says "pName must be the name of a supported command that has a first parameter of type VkDevice, VkQueue or VkCommandBuffer, either in the core API or an enabled extension". The `static if` in the `VkDevice` overload of `loadAllFunctions` filters out functions that do not meet this requirement (by using `std.traits.Parameters`), such as `vkDestroyInstance`.

(This also applies to your comment on #7)

**Comment by ParticlePeter** [comment]
Yes I missed that, but there is still an issue, maybe I oversee again something. Before VkDevice gets created, some functions need to be available e.g. functions which take a VkPhysicalDevice as first argument (vkGetPhysicalDeviceFoo()) to query the physical device extension/layers/features. With these results one chooses one or more of those devices create logical devices (VkDevices). AFAICS you either load all these functions through the instance and than again you could, but don't need to load them through the device, and overwrite them?

You really try hard to get all func pointers loaded with only two functions but it is a three level process:
1. Load functions from Driver/Implementation (Your loadInstanceFunctions). Query Extension/Layer availability and create an instance.
2. Load functions from Instance (stuffed into your loadAllFunctions). Query Physical Device Properties etc. and create a logical device (VkDevice)
3. Load functions directly from the logical device or indirectly through the instance (also stuffed into loadAllFunctions). Functions that have VkDevice, VkQueue or VkCommandBuffer as first argument

Additionally you apply D wizardry where none is required, all the above is solvable, and already solved, within python. Have you had a chance to look into erupted.functions module? Its clean, simple and does what should be done.

I admit that I changed a lot in vkdgen.py, but in the end it got closer to the Khronos generator. Its the way they are doing it, just compare.

**Comment by ColonelThirtyTwo** [comment]
> You really try hard to get all func pointers loaded with only two functions but it is a three level process:

Step 3 is optional. You can use the function pointers provided from the instance (in fact, you have to if you want to use more than one device)

> Additionally you apply D wizardry where none is required

What? Compile-time metaprogramming is one of the main selling points of D. In fact, the main reason there's a Python script at all is because D can't parse XML at compile time yet (at least with `std.xml`); otherwise I would use CTFE and templates and not involve Python at all.

**Comment by ParticlePeter** [comment]
> Step 3 is optional. 

Yes it is, and you steal that option from the end user.

> You can use the function pointers provided from the instance (in fact, you have to if you want to use more than one device)

No you don't. If you would have taken a look at erupted and API without secrets you would see a working solution.

> What? Compile-time metaprogramming is one of the main selling points of D.

Its not about Ds metaprogramming, its about its requirement in creating good bindings, which are nil.

> In fact, the main reason there's a Python script at all is because D can't parse XML at compile time yet (at least with std.xml); otherwise I would use CTFE and templates and not involve Python at all.

And write the converter from scratch, yes please, proceed. But I wouldn't use it, I like reading, checking and skimming through easy to read code. And I guess there are lot of D people who feel the same, but I guess you would have your fans as well.

In any case as mentioned already elsewhere, i don't see any consensus for us, lets split ways. I'll keep you as primary author to erupted, the project will stay. Good bye.
